// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function GetCLIConfigStatus():Promise<Record<string, boolean>>;

export function ProviderCreate(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string,arg6:Array<config.ModelMapping>):Promise<config.Provider>;

export function ProviderDelete(arg1:string):Promise<void>;

export function ProviderList():Promise<Array<config.Provider>>;

export function ProviderSetEnabled(arg1:string,arg2:boolean):Promise<void>;

export function ProviderUpdate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:string,arg7:Array<config.ModelMapping>):Promise<void>;

export function ProxyRestart():Promise<void>;

export function ProxyStart():Promise<void>;

export function ProxyStatus():Promise<main.ProxyStatus>;

export function ProxyStop():Promise<void>;

export function SettingsGet():Promise<config.AppSettings>;

export function SettingsUpdatePort(arg1:number):Promise<void>;

export function WriteCLIConfig(arg1:string):Promise<void>;
