// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearProxyLogs() {
  return window['go']['main']['App']['ClearProxyLogs']();
}

export function GetCLIConfigStatus() {
  return window['go']['main']['App']['GetCLIConfigStatus']();
}

export function GetProxyLogs() {
  return window['go']['main']['App']['GetProxyLogs']();
}

export function GetProxyLogsSizeKB() {
  return window['go']['main']['App']['GetProxyLogsSizeKB']();
}

export function ProviderCreate(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ProviderCreate'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ProviderDelete(arg1) {
  return window['go']['main']['App']['ProviderDelete'](arg1);
}

export function ProviderList() {
  return window['go']['main']['App']['ProviderList']();
}

export function ProviderSetEnabled(arg1, arg2) {
  return window['go']['main']['App']['ProviderSetEnabled'](arg1, arg2);
}

export function ProviderUpdate(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ProviderUpdate'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ProxyRestart() {
  return window['go']['main']['App']['ProxyRestart']();
}

export function ProxyStart() {
  return window['go']['main']['App']['ProxyStart']();
}

export function ProxyStatus() {
  return window['go']['main']['App']['ProxyStatus']();
}

export function ProxyStop() {
  return window['go']['main']['App']['ProxyStop']();
}

export function SettingsGet() {
  return window['go']['main']['App']['SettingsGet']();
}

export function SettingsUpdatePort(arg1) {
  return window['go']['main']['App']['SettingsUpdatePort'](arg1);
}

export function WriteCLIConfig(arg1) {
  return window['go']['main']['App']['WriteCLIConfig'](arg1);
}
